### ISSUE TITLE
Missing output cells of some testbed notebooks

### ISSUE THREAD

**Issue by jonglee1** [IN-CORE/incore-docs#155]
Missing output cells of some testbed notebooks
* galveston testbed: https://incore.ncsa.illinois.edu/doc/incore/notebooks/Galveston_testbed/Galveston_testbed.html
* joplin testbed: https://incore.ncsa.illinois.edu/doc/incore/notebooks/Joplin_testbed/Joplin_testbed.html

**Comment by navarroc** [comment]
Only fixing Joplin. Galveston should be handled as part of #163

**Comment by navarroc** [comment]
Fixed Galveston too since we will update the notebook in the next release.
