### ISSUE TITLE
MMSA notebook 2 has broken image links under Reference section

### ISSUE THREAD

**Issue by jonglee1** [IN-CORE/incore-docs#156]
MMSA notebook 2 has broken image links under Reference section

https://incore.ncsa.illinois.edu/doc/incore/notebooks/MMSA_testbed/MMSA_Seismic_Functionality_and_Restoration_Analysis_for_Interdependent_Buildings-Water-Power_using_Restoration_Curves.html

![image](https://user-images.githubusercontent.com/5861374/185241767-f2d22095-89d1-4495-81ef-75617530e3e4.png)

**Comment by navarroc** [comment]
Requested images that are missing. The original notebook didn't include them

**Comment by navarroc** [comment]
They don't have them, we should just remove the image references

**Comment by longshuicy** [comment]
Is this already addressed?
