### ISSUE TITLE
Update Joplin retrofit plan example notebook to use incore space hazards

### ISSUE THREAD

**Issue by navarroc** [IN-CORE/incore-docs#175]
The Joplin retrofit plan example notebook references tornado hazards in the researchers personal space. The example needs to be updatd to use incore space hazards so all users can run the notebook.

**Comment by longshuicy** [comment]
@nunezco2 do you mind I assign this to you?

**Comment by longshuicy** [comment]
add the id to "incore" might be easier

**Comment by navarroc** [comment]
Yes, I think we can probably just add the simulated tornado to the incore space since it's just a simulated tornado. Also, the hazards_list line of the notebook references tornadoes that no longer exist (I'm guessing the user deleted them). We should replace that too. 

For reference, the notebook is called retrofit_plan_Joplin_2021_12_01.ipynb and can be found in the manual_jb folder.
