### ISSUE TITLE
Update combined damage analysis documentation

### ISSUE THREAD

**Issue by navarroc** [IN-CORE/incore-docs#194]
Combined damage analysis combines three damage inputs into a single set of damage probabilities. We need to update the documentation page to reflect this change.

**Comment by longshuicy** [comment]
If you are too busy maybe @Vismayak can try help you on this?

**Comment by longshuicy** [comment]
Things to do:
1. Update the **Output datasets** session of the markdown file `manual_jb/content/analyses/combined_wind_wave_surge_building_dmg.md` to include one additional output dataset

You can check the pyincore analysis spec for more details: https://github.com/IN-CORE/pyincore/blob/develop/pyincore/analyses/combinedwindwavesurgebuildingdamage/combinedwindwavesurgebuildingdamage.py#L171


2. Update the jupyter notebook `/notebooks/combined_wind_wave_surge_building_dmg.ipynb`. You can cross compare with the combined wind wave surge section of the Galveston notebook to see if there is any content need to be updated:
https://github.com/IN-CORE/incore-docs/blob/6aeb383c4e2a6e63a872f5c70493157a7d1c1156/manual_jb/content/notebooks/galveston_community_app.ipynb

Just search "Combined Building Damage"
