### ISSUE TITLE
Update SLC community app notebook failure state keys

### ISSUE THREAD

**Issue by navarroc** [IN-CORE/incore-docs#226]
The slc_community_app.ipynb is using the old failure state key settings and don't match the released community app. The notebook is using:

DS1, DS2, DS3 for MCS buildings and DS1, DS2, DS3, DS4 for MCS-epf

This should be:

DS2, DS3 and DS2, DS3, DS4 respectively

**Comment by Rashmil-1999** [comment]
<img width="1095" alt="Screenshot 2023-04-19 at 1 17 49 PM" src="https://user-images.githubusercontent.com/32737711/233151162-92bb9d93-2fd5-46ea-bdab-27200ae38c71.png">
I tried running it as it is and it seems to run properly. To make the changes, you mean to change the 10th line in the topmost cell in this image right? it should be changed to `["DS_2", "DS_3"]` right?

**Comment by Rashmil-1999** [comment]
<img width="1178" alt="Screenshot 2023-04-19 at 1 20 23 PM" src="https://user-images.githubusercontent.com/32737711/233151771-201a7bd2-fce0-45aa-aaf4-2a5c755abf4e.png">
Also, I got this error when running the notebook.

**Comment by navarroc** [comment]
> <img alt="Screenshot 2023-04-19 at 1 17 49 PM" width="1095" src="https://user-images.githubusercontent.com/32737711/233151162-92bb9d93-2fd5-46ea-bdab-27200ae38c71.png">
> 
> I tried running it as it is and it seems to run properly. To make the changes, you mean to change the 10th line in the topmost cell in this image right? it should be changed to `["DS_2", "DS_3"]` right?

Yes, that's correct for buildings. We also need to change EPF to the other set of keys I mentioned.

**Comment by Rashmil-1999** [comment]
Okay, I see but for some reason the latest pyincore develop branch install gives me the probability not found error as you can see in the next comment :(

**Comment by navarroc** [comment]
> <img alt="Screenshot 2023-04-19 at 1 20 23 PM" width="1178" src="https://user-images.githubusercontent.com/32737711/233151771-201a7bd2-fce0-45aa-aaf4-2a5c755abf4e.png">
> 
> Also, I got this error when running the notebook.

ah, we need to fix that. We changed how those utilities worked. The utility now takes the output from MCS samples instead of mcs probability. I think you can look at the utility class unit test.
