### ISSUE TITLE
Update SLC community app notebook

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-docs#338]
### Update mappings with mapping keys
- [x] 6309005ad76c6d0e1f6be081 slc eq

> SLC
> 1 Strategy: Wood or Metal Deck Diaphragms
> Selection criteria: URMM or URML + percentage % + council zone + housing type + etc
> e.g. 20% random selected buildings in "residential zone", "multi-family", "built before year 1995", "URMM or URML" type -> retrofit.

### Create retrofit plan
- [x] Find the buildings belong to URMM and URML struct_typ
- [x] Pick 20% random of the buildings within the residential council zone --> don't know how to that for now
- [x] Just pick 20% for now
- [x] Assign them to "Wood or Metal Deck Diaphragms Retrofitted"
- [ ] Upload the plan file into incore and place them into SLC playbook space (**slc-app**)

### Update the SLC notebook
- [ ] Update to have the new CGE ML analyses
- [ ] Have an additional section running retrofitted building damage
- [ ] Merge back with baseline non-retrofitted building damage
- [ ] Compare all the downstream analyses retrofitted/non-retrofitted
- [ ] Benchmark the performance (just roughly estimating)

**Comment by Vismayak** [comment]
SLC retrofit id - 65fc9e6936b03d43385960b2

**Comment by longshuicy** [comment]
shorten it to WMDD
