### ISSUE TITLE
Improve the visualisation of the Buyout model notebook

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-docs#344]
Improve the visualisation fo the Buyout model notebook. 
Notebook will be used to demo in Galveston Community App workshop.

**Comment by Vismayak** [comment]
Have corrected the maps as requested by Farinaz. She has given me an updated notebook with the datafiles she uses. @longshuicy would my next steps be to move all the files she uses to the IN-CORE server? She does get the output of the files from Kooshan's Notebook on population dislocation but would be clunkier to add that code to the notebook 

[Buyout Model.zip](https://github.com/IN-CORE/incore-docs/files/14483648/Buyout.Model.zip)

**Comment by longshuicy** [comment]
> Have corrected the maps as requested by Farinaz. She has given me an updated notebook with the datafiles she uses. @longshuicy would my next steps be to move all the files she uses to the IN-CORE server? She does get the output of the files from Kooshan's Notebook on population dislocation but would be clunkier to add that code to the notebook
> 
> [Buyout Model.zip](https://github.com/IN-CORE/incore-docs/files/14483648/Buyout.Model.zip)

Sounds good. Make sure which space you can share those datasets with. Maybe you can ask her how comfortable with sharing those datasets to public space or she'd prefer keep it in her own space.

**Comment by Vismayak** [comment]
Waiting on Farinaz to confirm the notebook is good for the presentation
