### ISSUE TITLE
Look into the building functionality part of Joplin app

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/incore-docs#364]
>  I ran the three scenarios (100% retrofit 1, 100% retrofit 2, and 100% retrofit 3), and this page has no comparison difference. The trend of different scenarios makes sense for all the other pages/metrics.

Could we plugin the 100% RS1, 2, 3 file into the jupyter notebook and see if there is any differences. If there is differences and the playbook app is not reflecting that, we need to look closer on what's wrong with the app.

**Comment by longshuicy** [comment]
@navarroc Is it ok that I tentatively put this in the incore-docs repo? If after investigation there is no issue with our code, we can close this.

**Comment by ylyangtw** [comment]
How should I find the proper RS files?

**Comment by longshuicy** [comment]
Done.
